### ISSUE TITLE
repositories() ignores CRAN repo set in options(repos)

### ISSUE THREAD

**Issue by cboettig** [Bioconductor/BiocManager#69] opened 2020-05-14 02:49 UTC
I have a specific CRAN mirror set using the `repos` field in `options`, following the standard practice, but `BiocManager::repositories()` completely ignores this in favour of it's own defaults:

My settings:

```r
getOption("repos")
                                            CRAN 
"https://mran.microsoft.com/snapshot/2020-02-28" 
```

but:

```
> BiocManager::repositories()
                                                BioCsoft 
           "https://bioconductor.org/packages/3.10/bioc" 
                                                 BioCann 
"https://bioconductor.org/packages/3.10/data/annotation" 
                                                 BioCexp 
"https://bioconductor.org/packages/3.10/data/experiment" 
                                           BioCworkflows 
      "https://bioconductor.org/packages/3.10/workflows" 
                                                    CRAN 
                              "https://cran.rstudio.com" 
```

Why does BiocManager ignore my preferred repository?  How can I configure my own system default for my preferred repo, so that I don't have to pass a custom `site_repositories` value to `BiocManager::install()`?  

(For context here: Bioconductor is so good about locking it's own packages into nice stable releases.  It would be great to be able to accomplish the same thing with CRAN packages on which those depend.)

**Comment by jashapiro** [comment] 2020-05-14 14:17
I will add that passing a custom `site_repositories` value to `BiocManager::install()` is insufficient in its current form, as it prepends the repositories given to the list, and does not replace the default. This appears to result in taking the more recent version of each package across repositories, not the first among the listed repositories.

**Comment by mtmorgan** [comment] 2020-05-14 15:57
We'll revisit this.

The argument for using BiocManager::install() is to ensure that packages are installed from the same repositories as they are checked -- generally, Bioconductor packages have (until recently, anyway) had much deeper dependency graphs than CRAN packages, so pointing to old CRAN snapshots isn't a good idea. The primary goal is to standardize installation for average users, even if the average user does something that 'seemed like a good idea at the time'.

For reproducibility it seems one would want to include snapshots of Bioconductor packages, rather than a snapshot of 'just' CRAN packages. Maybe there's a different use case in mind?

I think the @jashapiro suggestion is that named `site_reposities=` replace their counterpart in `BiocManager::repositories()`?

FWIW, there is a base R way of specifying Bioc mirror, which I guess one could think of as 'official', but because of our 6 month release cycle, the base R specification is necessarily wrong 1/2 the time. So there is little to bind us to the approach to repository specification used in base R.

Again, though, we'll revisit this...

**Comment by cboettig** [comment] 2020-05-14 17:47
@mtmorgan If I run BiocManager::install() on a system running R 3.6.2, it cleverly  knows to use https://bioconductor.org/packages/3.10/bioc as the repository for BioC packages, insuring that I get the same BioC packages every time, right?

However, many of those packages have CRAN dependencies.  `BiocManager::repositories()` is very careful to make sure that the BioC dependencies are being satisfied from a repo whose package versions *are not changing*, i.e. from https://bioconductor.org/packages/3.10/bioc, but at the same time is assuming that the CRAN dependencies can be satisfied from RStudio's CRAN mirror of latest packages.  Obviously the versions listed at `https://cran.rstudio.com"` today do not match the versions that BioC 3.10 packages were built with.  To make this worse, it appears to be impossible to override BioC's choice of CRAN mirror with a custom mirror, such as MRAN, which would be stable.  

I think it would be best to simply avoid setting a CRAN value in the defaults set by `repositories()`.  This may be fine on `latest` release, but this is wrong 100% of the time on any older BioC release -- it points at bleeding edge CRAN, where the packages in question may have newer versions or may even have been removed.  

A second problem seems to be that there is no way to override the default CRAN repository if I want to.  An R user has a reasonable expectation that the value of "repos" set in `options` will work, but it does not.  i.e. I'd expect `BiocManager::repositories()` to inherit all repos listed by `getOptions("repos")`, but it ignores them.  

Nor can we even pass different values to `BiocManager::install()` manually.  `install()` takes only length-1 site_repository, so attempting to omit BioC default CRAN repo fails:

```r
# Just drop CRAN fails -- apparently install only cares about the first repo of BiocManger::repositories() ?
BiocManager::install("GenomicFeatures", site_repository=BiocManager::repositories()[1:4])
```
Error in BiocManager::install("GenomicFeatures", site_repository = BiocManager::repositories()[1:4]) : 
  length(site_repository) <= 1L is not TRUE


````r
# Adding an additional repo fails
BiocManager::install("GenomicFeatures", site_repository= c(BiocManager::repositories()[1], getOptions("repos"))
```

The only way I could get to install Bioc packages from the 3.10 BioC release using CRAN packages from a custom CRAN repo (such as the MRAN snapshot that actually matches what CRAN looked like at the time of the 3.10 release and not what it looks like today) is to rely on the base R approach:

```r
install.packages("GenomicFeatures", repos = c(BiocManager::repositories()[1], getOption('repos')))
``` 

where my MRAN mirror has been set in the standard way in options.  (Note that this approach also respects the use of other additional repositories, which may be suggested dependencies of CRAN packages, e.g., from OmegaHat.net).



I really admire the BioC release model -- it avoids many of the challenges of CRAN's bleeding-edge release model, and avoids the need for third-party mirrors like MRAN or RSPM to provide version-stable packages.  However, that doesn't do much good if CRAN deps are hardwired to come from https://cran.rstudio.com, right?

**Comment by mtmorgan** [comment] 2020-05-16 16:52
`BiocManager::install()` is aiming at the basic R user, who doesn't want to know about / often makes the wrong choice choosing a CRAN mirror. Also, the default value for CRAN is the mirror Bioconductor is built and checked against. So setting a default is appropriate.

You're right that BiocManager is wrong for out-of-date releases, and that should be improved.

And certainly, setting a CRAN repository to something different from the default seems appropriate for reproducibility and other reasons, once one is confident that the use is consistent (or better than!) Bioconductor best practice.

This updated [pull request][1] (thanks @LiNk-NY for starting) behaves as follows.

[1]: https://github.com/Bioconductor/BiocManager/pull/70

- `carl1` sets `options(repos = c(CRAN="https://foo.bar"))`. The result is

    ```{r}
    > options(repos = c(CRAN="https://foo.bar"))
    > repositories()
    Error: 'getOption("repos")' replaces Bioconductor standard repositories, see
    '?repositories' for details

    replacement repositories:
        CRAN: https://foo.bar
    ```

- Consulting the suggested help page, `carl2` does

    ```{r}
    > options(repos = c(CRAN="https://foo.bar"), BiocManager.check_repositories = FALSE)
    > repos = repositories()
    'getOption("repos")' replaces Bioconductor standard repositories, see
    '?repositories' for details

    replacement repositories:
        CRAN: https://foo.bar

    > repos
                                                    BioCsoft
               "https://bioconductor.org/packages/3.12/bioc"
                                                     BioCann
    "https://bioconductor.org/packages/3.12/data/annotation"
                                                     BioCexp
    "https://bioconductor.org/packages/3.12/data/experiment"
                                               BioCworkflows
          "https://bioconductor.org/packages/3.12/workflows"
                                                        CRAN
                                           "https://foo.bar"
     ```

I made this `stop()` (instead of warning) because a warning would only be displayed after the user had messed up their bioc installation (more likely the user would ignore the warning in the barrage of outputs from installing packages). I continue to print a `message()` so that when users report problems, we have a chance to see that they are using a non-standard repository; `suppressMessages()` would silence the message.

There are (unrelated) tweaks to `site_repository = ` for a separate pull request.

**Comment by hpages** [comment] 2020-05-16 21:08
How about having `BiocManager::repositories()[["CRAN"]]` **automatically** point to a MRAN snapshot for old BioC releases?

E.g. in BioC 3.10, it would be:
```
> BiocManager::repositories()[["CRAN"]]
[1] "https://mran.microsoft.com/snapshot/2020-04-15"
```
In BioC 3.9:
```
> BiocManager::repositories()[["CRAN"]]
[1] "https://mran.microsoft.com/snapshot/2019-10-16"
```
etc...

The exact date of the snapshot would be the date when the branch got frozen.

**Comment by mtmorgan** [comment] 2020-05-17 21:35
Yes @hpages I was thinking the same thing. The release dates are available from https://bioconductor.org/config.yaml . The last build dates could be scraped (once, and added to config.yaml?) from https://bioconductor.org/checkResults/ but is there another location?

Are there any concerns about the stability of mran? (I guess not...)

**Comment by hpages** [comment] 2020-05-17 22:07
I don't know of another location for scrapping the last build dates. These dates should probably be stored in https://bioconductor.org/config.yaml so it would be a one time scrapping anyway. Can even be a manual scrapping.

I'm also concerned about the perennity of MRAN. It will disappear the day Microsoft looses its interest in supporting the R ecosystem. Could happen in 2 years or in 20 years from now, who knows. Despite this uncertainty I still see this solution as an improvement over the current situation where it's practically impossible to install an old version of Bioconductor. So even the worst case scenario (i.e. MRAN disappears and we edit config.yaml to point to current CRAN) wouldn't be worse than the current situation.

**Comment by cboettig** [comment] 2020-05-18 00:11
Thanks @mtmorgan @hpages, this sounds great. 

Regarding sustainability, RStudio is also offering CRAN snapshots, not quite daily but close, see https://packagemanager.rstudio.com/client/#/.

**Comment by mtmorgan** [comment] 2020-05-23 20:06
I'll close this issue with an update respecting `options(repos=)`. I'll open a separate issue for the more extensive change to choose a better repository for out-of-date releases of Bioconductor.

**Closed** 2020-05-23 20:09 UTC
